FROM arm64v8/golang:1.12 as builder
MAINTAINER xiliangMa "xiliangMa@outlook.com"
EXPOSE 8080
EXPOSE 8088
EXPOSE 10443
WORKDIR /build
COPY entrypoint.sh .
COPY bin/diss-backend .
COPY conf ./conf
COPY swagger ./swagger

FROM arm64v8/alpine:3.11
WORKDIR /opt/diss-backend
COPY --from=builder /build/ .
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["sh", "./entrypoint.sh"]
